print ("     BILL SPLITTING PROGRAM")
bill = int(input("Enter amount of bill"))
nmbr = int(input("Enter number of pepolepaying the bill"))
split = round(float(bill / nmbr), 2)
print("Amount to be paid by person: ", split)